src/WebApp/WebApp/Models/ClassificadoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class ClassificadoViewModel
    {
        [DisplayName("Título")]
        public string Nome { get; set; }
        [DisplayName("Data de Nascimento")]
        public DateTime DataDeNascimento { get; set; }
        public string Sexo { get; set; }
        [DisplayName("E-mail")]
        public string Email { get; set; }
        public string Telefone { get; set; }
        [DisplayName("Endereço")]
        public string Endereco { get; set; }
        [DisplayName("Descrição")]
        public string Descricao { get; set; }
        public string Valor { get; set; }
        public string Tipo { get; set; }
    }
}

src/WebApp/WebApp/Models/ClienteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class ClienteViewModel
    {
        [Required(ErrorMessage ="O campo Nome é obrigatório")]
        [StringLength(100, ErrorMessage = "O nome precisa ter no mínimo 5 letras",MinimumLength = 5)]
        public string Nome { get; set; }

        public string Sexo { get; set; }

        [DisplayName("Data de Nascimento")]
        [Required(ErrorMessage = "O campo Data de Nascimento é obrigatório")]
        public DateTime DataDeNascimento { get; set; }

        [DisplayName("e-Mail")]
        [Required(ErrorMessage = "O campo e-Mail é obrigatório")]
        [EmailAddress(ErrorMessage = "Email está em um formato incorreto!")]
        public string Email { get; set; }

        public string Telefone { get; set; }

        [DisplayName("Endereço")]
        public string Endereco { get; set; }

    }
}

src/WebApp/WebApp/Models/ConteudoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class ConteudoViewModel
    {
        [DisplayName("Título")]
        public string Titulo { get; set; }
        [DisplayName("Data do Cadastro")]
        public DateTime DataDoCadastro { get; set; }
        public string Texto { get; set; }
        [DisplayName("Link da imagem")]
        public string LinkImagem { get; set; }
        [DisplayName("Descrição")]
        public string Descricao { get; set; }     
        [DisplayName("Nome do autor")]
        public string NomeAutor { get; set; }
        public string Linkedin { get; set; }
        
    }
    
}

src/WebApp/WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/WebApp/WebApp/Controllers/ClassificadosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ClassificadosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Novo(ClassificadoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var classificados = model;
                return RedirectToAction("Index");
            }

            return View(model);
        }

       
    }
}

src/WebApp/WebApp/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Novo(ClienteViewModel model)
        {
            if(ModelState.IsValid)
            {
                var cliente = model;
                return RedirectToAction("Index");
            }

            return View(model);
;        }
    }
}

src/WebApp/WebApp/Controllers/ConteudoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ConteudoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Novo(ConteudoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var conteudo = model;
                return RedirectToAction("Index");
            }

            return View(model);
        }

    }
}

src/WebApp/WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

src/WebApp/WebApp/Views/Classificados/Index.cshtml
<h1>Lista de Classificados</h1>

<div class="row">
    <div class="col-md-2">
        <a class="btn btn-info" asp-controller="Classificados" asp-action="Novo">Novo</a>
    </div>
</div>

src/WebApp/WebApp/Views/Classificados/Novo.cshtml
@model WebApp.Models.ClassificadoViewModel

<h1>Cadastro de Classificados</h1>

<form asp-action="Novo">
    <div class="card">
        <div class="card-header">Dados do Classificados</div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Nome"></label>
                    <input type="text" asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="DataDeNascimento"></label>
                    <input type="date" asp-for="DataDeNascimento" class="form-control" />
                    <span asp-validation-for="DataDeNascimento" class="text-danger"></span>
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Sexo"></label>
                    <select asp-for="Sexo" class="form-control">
                        <option>Selecione</option>
                        <option value="Masculino">Masculino</option>
                        <option value="Feminino">Feminino</option>
                        <option value="Outros">Outros</option>
                    </select>
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Email"></label>
                    <input type="text" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Endereco"></label>
                    <input type="text" asp-for="Endereco" class="form-control" />
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Telefone"></label>
                    <input type="text" asp-for="Telefone" class="form-control" />
                </div>
            </div>
    </div>
            <div class="card">
                <div class="card-header">Produto</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            <label asp-for="Descricao"></label>
                            <input type="text" asp-for="Descricao" class="form-control" />
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <label asp-for="Valor"></label>
                            <input type="text" asp-for="Valor" class="form-control" />
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <label asp-for="Tipo"></label>
                            <input type="text" asp-for="Tipo" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-2">
                            <input type="submit" value="Gravar" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>

<hr />

<div class="row">
    <div class="col-md-2">
        <a class="btn btn-dark" asp-controller="Cliente" asp-action="Index">Voltar</a>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/WebApp/WebApp/Views/Cliente/Index.cshtml
<h1>Lista de Clientes</h1>

<div class="row">
    <div class="col-md-2">
        <a class="btn btn-info" asp-controller="Cliente" asp-action="Novo">Novo</a>
    </div>
</div>

src/WebApp/WebApp/Views/Cliente/Novo.cshtml
@model WebApp.Models.ClienteViewModel

<h1>Cadastro de Clientes</h1>

<form asp-action="Novo">
    <div class="card">
        <div class="card-header">Dados do Cliente</div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Nome"></label>
                    <input type="text" asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Sexo"></label>
                    <select asp-for="Sexo" class="form-control">
                        <option>Selecione</option>
                        <option value="Masculino">Masculino</option>
                        <option value="Feminino">Feminino</option>
                        <option value="Outros">Outros</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <label asp-for="DataDeNascimento"></label>
                    <input type="date" asp-for="DataDeNascimento" class="form-control" />
                    <span asp-validation-for="DataDeNascimento" class="text-danger"></span>
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Email"></label>
                    <input type="text" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Telefone"></label>
                    <input type="text" asp-for="Telefone" class="form-control" />
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Endereco"></label>
                    <input type="text" asp-for="Endereco" class="form-control" />
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-md-2">
                    <input type="submit" value="Gravar" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
</form>

<hr />

<div class="row">
    <div class="col-md-2">
        <a class="btn btn-dark" asp-controller="Cliente" asp-action="Index">Voltar</a>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/WebApp/WebApp/Views/Conteudo/Index.cshtml
<h1>Lista de Conteúdos</h1>
<div class="row">
    <div class="col-md-2">
        <a class="btn btn-info" asp-controller="Conteudo" asp-action="Novo">Novo</a>
    </div>
</div>

src/WebApp/WebApp/Views/Conteudo/Novo.cshtml
@model WebApp.Models.ConteudoViewModel
<h1>Cadastro de Conteúdo</h1>

<form asp-action="Novo">
    <div class="card">
        <div class="card-header">Dados do Conteúdo</div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <label asp-for="Titulo"></label>
                    <input type="text" asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>
                <div class="col-md-4 col-sm-12">
                    <label asp-for="DataDoCadastro"></label>
                    <input type="date" asp-for="DataDoCadastro" class="form-control" />
                    <span asp-validation-for="DataDoCadastro" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <label asp-for="Texto"></label>
                    <input type="text" asp-for="Texto" class="form-control" />
                    <span asp-validation-for="Texto" class="text-danger"></span>
                </div>
                <div class="col-md-6 col-sm-12">
                    <label asp-for="LinkImagem"></label>
                    <input type="text" asp-for="LinkImagem" class="form-control" />
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">Tipo de conteúdo</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <label asp-for="Descricao"></label>
                        <input type="text" asp-for="Descricao" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">Autor</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            <label asp-for="NomeAutor"></label>
                            <input type="text" asp-for="NomeAutor" class="form-control" />
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <label asp-for="Linkedin"></label>
                            <input type="text" asp-for="Linkedin" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-2">
                            <input type="submit" value="Gravar" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<hr />

<div class="row">
    <div class="col-md-2">
        <a class="btn btn-dark" asp-controller="Cliente" asp-action="Index">Voltar</a>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/WebApp/WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo! Ao site de Notícias</h1>
</div>

src/WebApp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Conteudo" asp-action="Index">Conteúdo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Classificados" asp-action="Index">Classificados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>